/* The following code was generated by JFlex 1.6.1 */

/*
    SmileBASIC Lexic Analyzer by StrScr
    To be used with CUP.
*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/oscar/OneDrive - Universidad Tecnologica Centroamericana/UNITEC/4-3/Compiladores I/Project/standalone_lexer.jflex</tt>
 */
class SLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\12\1\50\1\13"+
    "\1\63\1\61\1\62\1\53\1\6\1\41\1\42\1\57\1\55\1\45"+
    "\1\56\1\0\1\60\12\5\1\46\1\0\1\51\1\47\1\52\2\0"+
    "\1\32\1\35\1\34\1\25\1\10\1\16\1\4\1\20\1\15\1\4"+
    "\1\37\1\22\1\11\1\21\1\26\1\27\1\4\1\7\1\24\1\17"+
    "\1\33\1\40\1\31\1\30\2\4\1\43\1\0\1\44\1\0\1\4"+
    "\1\0\1\32\1\35\1\34\1\25\1\10\1\16\1\4\1\20\1\15"+
    "\1\4\1\37\1\22\1\11\1\21\1\26\1\27\1\4\1\7\1\24"+
    "\1\17\1\33\1\40\1\31\1\30\2\4\1\0\1\54\263\0\2\14"+
    "\115\0\1\23\u1faa\0\1\36\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\3\2\4"+
    "\1\6\1\1\4\4\1\1\11\4\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\2\1"+
    "\1\21\1\22\1\23\1\24\1\25\2\26\1\27\1\30"+
    "\1\31\1\4\1\3\3\4\1\32\1\0\1\32\5\4"+
    "\1\33\1\4\2\0\3\4\1\0\11\4\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\3\4\1\42\1\0\1\4"+
    "\2\43\1\44\4\4\3\0\3\4\1\45\1\46\2\47"+
    "\1\50\1\0\2\4\1\0\4\4\1\51\2\4\1\0"+
    "\1\4\2\52\1\0\1\4\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\56\1\57\1\60\1\0\1\4\1\61"+
    "\1\0\1\4\1\0\5\4\1\54\1\0\1\4\2\62"+
    "\2\63\2\64\2\65\1\0\1\4\2\66\1\67\1\70"+
    "\2\71\1\0\1\4\1\0\1\4\2\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\150\0\150\0\320\0\u0104"+
    "\0\u0138\0\u016c\0\u01a0\0\150\0\u01d4\0\u0208\0\u023c\0\u0270"+
    "\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410"+
    "\0\u0444\0\u0478\0\u04ac\0\150\0\150\0\150\0\150\0\150"+
    "\0\150\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4\0\150"+
    "\0\150\0\150\0\150\0\u0618\0\u064c\0\150\0\150\0\150"+
    "\0\150\0\150\0\u0680\0\u06b4\0\u06e8\0\u071c\0\150\0\u0750"+
    "\0\320\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u0854\0\320\0\u0888"+
    "\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u0a28"+
    "\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\150"+
    "\0\150\0\150\0\150\0\150\0\150\0\u0bc8\0\u0bfc\0\u0c30"+
    "\0\u0c64\0\u0c98\0\u0ccc\0\150\0\320\0\320\0\u0d00\0\u0d34"+
    "\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4"+
    "\0\320\0\320\0\150\0\320\0\320\0\u0f08\0\u0f3c\0\u0f70"+
    "\0\u0fa4\0\u0fd8\0\u100c\0\u1040\0\u1074\0\320\0\u10a8\0\u10dc"+
    "\0\u1110\0\u1144\0\u1178\0\u11ac\0\u11e0\0\u1214\0\320\0\320"+
    "\0\320\0\150\0\150\0\150\0\320\0\320\0\320\0\u1248"+
    "\0\u127c\0\320\0\u12b0\0\u12e4\0\u1318\0\u134c\0\u1380\0\u13b4"+
    "\0\u13e8\0\u141c\0\150\0\u1450\0\u1484\0\150\0\320\0\150"+
    "\0\320\0\150\0\320\0\150\0\320\0\u14b8\0\u14ec\0\150"+
    "\0\320\0\320\0\320\0\150\0\320\0\u1520\0\u1554\0\u1588"+
    "\0\u15bc\0\150\0\320";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\7\1\6\1\14\1\15\1\16\1\17\1\20"+
    "\1\7\1\21\1\7\1\22\1\23\1\24\1\25\1\26"+
    "\1\7\1\27\1\7\1\30\1\31\1\32\1\3\1\7"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\3\3\1\54\1\55\1\56\10\54\1\57\50\54"+
    "\66\0\1\5\65\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\12\7\1\0\2\7\20\0\1\60\1\61\1\62"+
    "\5\0\1\10\56\0\1\11\1\63\1\6\61\11\4\0"+
    "\2\7\1\0\1\7\1\64\1\7\3\0\6\7\1\0"+
    "\12\7\1\0\2\7\20\0\1\60\1\61\1\62\4\0"+
    "\2\7\1\0\3\7\3\0\4\7\1\65\1\66\1\0"+
    "\12\7\1\0\2\7\20\0\1\60\1\61\1\62\16\0"+
    "\1\67\2\0\1\70\46\0\2\7\1\0\3\7\3\0"+
    "\1\7\1\71\2\7\1\72\1\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\3\0\6\7\1\0\2\7\1\73\3\7\1\74"+
    "\3\7\1\0\2\7\20\0\1\60\1\61\1\62\4\0"+
    "\2\7\1\0\1\75\2\7\3\0\3\7\1\76\2\7"+
    "\1\0\2\7\1\77\7\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\1\7\1\100\1\7"+
    "\3\0\6\7\1\0\12\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\17\0\1\101\11\0\1\102\36\0\2\7"+
    "\1\0\3\7\3\0\2\7\1\103\3\7\1\0\5\7"+
    "\1\104\4\7\1\0\2\7\20\0\1\60\1\61\1\62"+
    "\4\0\2\7\1\0\1\7\1\105\1\7\2\0\1\106"+
    "\1\107\5\7\1\0\12\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\7\7\1\110\2\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\1\111\2\7\3\0"+
    "\6\7\1\0\12\7\1\0\2\7\20\0\1\60\1\61"+
    "\1\62\4\0\2\7\1\0\1\7\1\112\1\7\3\0"+
    "\3\7\1\113\2\7\1\0\12\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\3\7\3\0"+
    "\4\7\1\114\1\7\1\0\12\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\3\7\3\0"+
    "\6\7\1\0\2\7\1\115\7\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\1\116\2\7"+
    "\3\0\6\7\1\0\12\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\6\7\1\117\3\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\47\0\1\120\63\0\1\121\63\0\1\122"+
    "\63\0\1\123\67\0\1\124\64\0\1\125\7\0\1\54"+
    "\2\0\10\54\1\0\50\54\2\0\1\56\63\0\1\6"+
    "\65\0\2\7\1\0\2\7\1\126\3\0\2\7\1\127"+
    "\3\7\1\0\3\7\1\130\6\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\3\7\3\0"+
    "\6\7\1\0\1\7\1\131\10\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\3\7\3\0"+
    "\6\7\1\132\1\133\11\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\34\0\1\134\33\0\2\7\1\0\3\7"+
    "\3\0\6\7\1\0\10\7\1\135\1\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\4\0\2\7\1\0\1\136"+
    "\2\7\3\0\6\7\1\0\12\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\3\7\3\0"+
    "\5\7\1\137\1\0\12\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\7\7\1\140\2\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\1\7\1\141\1\7"+
    "\3\0\6\7\1\0\12\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\4\7\1\142\5\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\10\0\1\143\15\0\1\144\67\0\1\145"+
    "\35\0\2\7\1\0\1\7\1\146\1\7\3\0\6\7"+
    "\1\0\2\7\1\147\7\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\6\7\1\150\3\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\3\7\3\0\1\7"+
    "\1\151\4\7\1\0\10\7\1\152\1\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\11\0\1\153\56\0\2\7"+
    "\1\0\2\7\1\154\3\0\6\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\3\0\2\7\1\155\3\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\2\0\1\156\1\157\5\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\3\0\4\7\1\160\1\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\2\0\1\161\1\162\5\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\3\0\2\7\1\163\3\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\3\0\4\7\1\164\1\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\1\7\1\165\1\7\3\0\6\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\1\166\2\7\3\0\6\7\1\0\12\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\4\0\2\7\1\0\3\7"+
    "\1\11\2\0\6\7\1\0\12\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\3\7\3\0"+
    "\6\7\1\0\7\7\1\167\2\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\1\7\1\170"+
    "\1\7\3\0\6\7\1\0\12\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\4\0\2\7\1\0\3\7\2\0"+
    "\1\171\1\172\5\7\1\0\12\7\1\0\2\7\20\0"+
    "\1\60\1\61\1\62\10\0\1\173\57\0\2\7\1\0"+
    "\1\7\1\174\1\7\3\0\6\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\3\0\6\7\1\175\1\176\11\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\4\0\2\7\1\0\1\7"+
    "\1\177\1\7\3\0\6\7\1\0\12\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\4\0\2\7\1\0\3\7"+
    "\3\0\4\7\1\200\1\7\1\0\12\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\4\0\2\7\1\0\3\7"+
    "\3\0\2\7\1\201\3\7\1\0\12\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\27\0\1\202\63\0\1\203"+
    "\63\0\1\204\40\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\3\7\1\205\6\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\3\7\1\206\6\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\4\0\2\7\1\0\3\7\3\0\6\7"+
    "\1\0\3\7\1\207\6\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\21\0\1\210\46\0\2\7\1\0\3\7"+
    "\3\0\4\7\1\211\1\7\1\0\12\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\4\0\2\7\1\0\3\7"+
    "\3\0\6\7\1\0\1\7\1\212\10\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\22\0\1\213\45\0\2\7"+
    "\1\0\3\7\3\0\5\7\1\214\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\2\0\1\215\1\216\5\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\3\0\2\7\1\217\3\7\1\0\12\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\3\7\3\0\6\7\1\0\6\7\1\220\3\7\1\0"+
    "\2\7\20\0\1\60\1\61\1\62\4\0\2\7\1\0"+
    "\1\221\2\7\3\0\6\7\1\0\12\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\4\0\2\7\1\0\3\7"+
    "\3\0\6\7\1\0\6\7\1\222\3\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\16\0\1\223\51\0\2\7"+
    "\1\0\3\7\3\0\1\7\1\200\4\7\1\0\12\7"+
    "\1\0\2\7\20\0\1\60\1\61\1\62\14\0\2\224"+
    "\52\0\2\7\1\0\3\7\2\0\1\224\1\225\5\7"+
    "\1\0\12\7\1\0\2\7\20\0\1\60\1\61\1\62"+
    "\10\0\1\226\57\0\2\7\1\0\1\7\1\227\1\7"+
    "\3\0\6\7\1\0\12\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\17\0\1\230\50\0\2\7\1\0\3\7"+
    "\3\0\2\7\1\231\3\7\1\0\12\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\10\0\1\232\57\0\2\7"+
    "\1\0\1\7\1\233\1\7\3\0\6\7\1\0\12\7"+
    "\1\0\2\7\20\0\1\60\1\61\1\62\22\0\1\234"+
    "\45\0\2\7\1\0\3\7\3\0\5\7\1\235\1\0"+
    "\12\7\1\0\2\7\20\0\1\60\1\61\1\62\4\0"+
    "\2\7\1\0\3\7\2\0\1\236\1\237\5\7\1\0"+
    "\12\7\1\0\2\7\20\0\1\60\1\61\1\62\4\0"+
    "\2\7\1\0\3\7\3\0\6\7\1\0\12\7\1\240"+
    "\1\241\1\7\20\0\1\60\1\61\1\62\4\0\2\7"+
    "\1\0\3\7\3\0\4\7\1\242\1\7\1\0\12\7"+
    "\1\0\2\7\20\0\1\60\1\61\1\62\4\0\2\7"+
    "\1\0\3\7\3\0\2\7\1\243\3\7\1\0\12\7"+
    "\1\0\2\7\20\0\1\60\1\61\1\62\16\0\1\244"+
    "\51\0\2\7\1\0\3\7\3\0\1\7\1\245\4\7"+
    "\1\0\12\7\1\0\2\7\20\0\1\60\1\61\1\62"+
    "\21\0\1\246\46\0\2\7\1\0\3\7\3\0\4\7"+
    "\1\247\1\7\1\0\12\7\1\0\2\7\20\0\1\60"+
    "\1\61\1\62\33\0\1\250\34\0\2\7\1\0\3\7"+
    "\3\0\6\7\1\0\7\7\1\251\2\7\1\0\2\7"+
    "\20\0\1\60\1\61\1\62\10\0\1\252\57\0\2\7"+
    "\1\0\1\7\1\253\1\7\3\0\6\7\1\0\12\7"+
    "\1\0\2\7\20\0\1\60\1\61\1\62";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5616];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\2\11\5\1\1\11\17\1\6\11"+
    "\6\1\4\11\2\1\5\11\4\1\1\11\1\0\10\1"+
    "\2\0\3\1\1\0\11\1\6\11\4\1\1\0\1\1"+
    "\1\11\6\1\3\0\5\1\1\11\2\1\1\0\2\1"+
    "\1\0\7\1\1\0\3\1\1\0\4\1\3\11\3\1"+
    "\1\0\2\1\1\0\1\1\1\0\5\1\1\11\1\0"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\0\1\1\1\11\3\1\1\11\1\1\1\0"+
    "\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuilder string = new StringBuilder();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  SLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 222) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("LEXIC ERROR on line "+yyline+", column "+yycolumn+": I don't know what this is!: "+yytext());
            }
          case 59: break;
          case 2: 
            { System.out.println("<LINEEND>");
            }
          case 60: break;
          case 3: 
            { 
            }
          case 61: break;
          case 4: 
            { System.out.println("<IDENTIFIER_INTEGER, " + yytext() + ">");
            }
          case 62: break;
          case 5: 
            { System.out.println("<NUMBER, " + yytext() + ">");
            }
          case 63: break;
          case 6: 
            { yybegin(STRING); string.setLength(0);
            }
          case 64: break;
          case 7: 
            { System.out.println("<LPAREN>");
            }
          case 65: break;
          case 8: 
            { System.out.println("<RPAREN>");
            }
          case 66: break;
          case 9: 
            { System.out.println("<LBRACK>");
            }
          case 67: break;
          case 10: 
            { System.out.println("<RBRACK>");
            }
          case 68: break;
          case 11: 
            { System.out.println("<COMMA>");
            }
          case 69: break;
          case 12: 
            { System.out.println("<COLON>");
            }
          case 70: break;
          case 13: 
            { System.out.println("<EQ>");
            }
          case 71: break;
          case 14: 
            { System.out.println("<NOT>");
            }
          case 72: break;
          case 15: 
            { System.out.println("<LT>");
            }
          case 73: break;
          case 16: 
            { System.out.println("<GT>");
            }
          case 74: break;
          case 17: 
            { System.out.println("<PLUS>");
            }
          case 75: break;
          case 18: 
            { System.out.println("<MINUS>");
            }
          case 76: break;
          case 19: 
            { System.out.println("<MULT>");
            }
          case 77: break;
          case 20: 
            { System.out.println("<DIV>");
            }
          case 78: break;
          case 21: 
            { string.append( yytext() );
            }
          case 79: break;
          case 22: 
            { throw new RuntimeException("Unterminated string at end of line "+yyline);
            }
          case 80: break;
          case 23: 
            { yybegin(YYINITIAL); System.out.println("<STRING_LITERAL, " + string.toString() + ">");
            }
          case 81: break;
          case 24: 
            { System.out.println("<IDENTIFIER_STRING, " + yytext() + ">");
            }
          case 82: break;
          case 25: 
            { System.out.println("<IDENTIFIER_DECIMAL, " + yytext() + ">");
            }
          case 83: break;
          case 26: 
            { System.out.println("<IF>");
            }
          case 84: break;
          case 27: 
            { System.out.println("<TO>");
            }
          case 85: break;
          case 28: 
            { System.out.println("<EQEQ>");
            }
          case 86: break;
          case 29: 
            { System.out.println("<NOTEQ>");
            }
          case 87: break;
          case 30: 
            { System.out.println("<LTEQ>");
            }
          case 88: break;
          case 31: 
            { System.out.println("<GTEQ>");
            }
          case 89: break;
          case 32: 
            { System.out.println("<ANDAND>");
            }
          case 90: break;
          case 33: 
            { System.out.println("<OROR>");
            }
          case 91: break;
          case 34: 
            { System.out.println("<END>");
            }
          case 92: break;
          case 35: 
            { System.out.println("<INC>");
            }
          case 93: break;
          case 36: 
            { System.out.println("<FOR>");
            }
          case 94: break;
          case 37: 
            { System.out.println("<DEF>");
            }
          case 95: break;
          case 38: 
            { System.out.println("<DEC>");
            }
          case 96: break;
          case 39: 
            { System.out.println("<DIM>");
            }
          case 97: break;
          case 40: 
            { System.out.println("<OUT>");
            }
          case 98: break;
          case 41: 
            { System.out.println("<VAR>");
            }
          case 99: break;
          case 42: 
            { System.out.println("<ELSE>");
            }
          case 100: break;
          case 43: 
            { System.out.println("<TRUE>");
            }
          case 101: break;
          case 44: 
            { System.out.println("<THEN>");
            }
          case 102: break;
          case 45: 
            { System.out.println("<NEXT>");
            }
          case 103: break;
          case 46: 
            { System.out.println("<STEP>");
            }
          case 104: break;
          case 47: 
            { System.out.println("<STOP>");
            }
          case 105: break;
          case 48: 
            { System.out.println("<SWAP>");
            }
          case 106: break;
          case 49: 
            { System.out.println("<WEND>");
            }
          case 107: break;
          case 50: 
            { System.out.println("<FALSE>");
            }
          case 108: break;
          case 51: 
            { System.out.println("<PRINT>");
            }
          case 109: break;
          case 52: 
            { System.out.println("<WHILE>");
            }
          case 110: break;
          case 53: 
            { System.out.println("<UNTIL>");
            }
          case 111: break;
          case 54: 
            { System.out.println("<BREAK>");
            }
          case 112: break;
          case 55: 
            { System.out.println("<RETURN>");
            }
          case 113: break;
          case 56: 
            { System.out.println("<REPEAT>");
            }
          case 114: break;
          case 57: 
            { System.out.println("<ELSEIF>");
            }
          case 115: break;
          case 58: 
            { System.out.println("<CONTINUE>");
            }
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java SLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        SLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new SLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
