
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package JSmileBASIC;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GT = 50;
  public static final int WON = 10;
  public static final int WEND = 16;
  public static final int NOTEQ = 47;
  public static final int UNTIL = 18;
  public static final int NEXT = 14;
  public static final int RBRACK = 42;
  public static final int COMMA = 43;
  public static final int BIT_AND = 61;
  public static final int RPAREN = 40;
  public static final int LBRACK = 41;
  public static final int LT = 48;
  public static final int ANDAND = 53;
  public static final int OROR = 54;
  public static final int BIT_XOR = 63;
  public static final int LPAREN = 39;
  public static final int OUT = 26;
  public static final int FALSE = 38;
  public static final int NOT = 52;
  public static final int DEF = 23;
  public static final int ELSEIF = 5;
  public static final int DEC = 31;
  public static final int VAR = 28;
  public static final int THEN = 3;
  public static final int GOTO = 21;
  public static final int IDENTIFIER_INTEGER = 72;
  public static final int INTEGER_DIV = 60;
  public static final int LINPUT = 36;
  public static final int EQ = 45;
  public static final int MOD = 59;
  public static final int NUMBER = 67;
  public static final int TRUE = 37;
  public static final int SWAP = 32;
  public static final int PLUS = 55;
  public static final int QUESTION = 34;
  public static final int WHILE = 15;
  public static final int DECIMAL = 68;
  public static final int INPUT = 35;
  public static final int BIT_NOT = 64;
  public static final int FOR = 11;
  public static final int DIV = 58;
  public static final int BIT_OR = 62;
  public static final int RETURN = 25;
  public static final int MULT = 57;
  public static final int ELSE = 4;
  public static final int BREAK = 20;
  public static final int GTEQ = 51;
  public static final int IDENTIFIER_DECIMAL = 71;
  public static final int DIM = 29;
  public static final int EQEQ = 46;
  public static final int EOF = 0;
  public static final int SEMICOLON = 44;
  public static final int DEFAULT = 9;
  public static final int PRINT = 33;
  public static final int ENDIF = 6;
  public static final int INC = 30;
  public static final int REPEAT = 17;
  public static final int LABEL = 73;
  public static final int MINUS = 56;
  public static final int LTEQ = 49;
  public static final int LINEEND = 74;
  public static final int IDENTIFIER_STRING = 70;
  public static final int error = 1;
  public static final int ON = 7;
  public static final int CONTINUE = 19;
  public static final int IF = 2;
  public static final int END = 27;
  public static final int COLON = 75;
  public static final int CASE = 8;
  public static final int RSHIFT = 66;
  public static final int STRING = 69;
  public static final int STEP = 13;
  public static final int GOSUB = 22;
  public static final int UMINUS = 76;
  public static final int TO = 12;
  public static final int LSHIFT = 65;
  public static final int CALL = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "ELSEIF",
  "ENDIF",
  "ON",
  "CASE",
  "DEFAULT",
  "WON",
  "FOR",
  "TO",
  "STEP",
  "NEXT",
  "WHILE",
  "WEND",
  "REPEAT",
  "UNTIL",
  "CONTINUE",
  "BREAK",
  "GOTO",
  "GOSUB",
  "DEF",
  "CALL",
  "RETURN",
  "OUT",
  "END",
  "VAR",
  "DIM",
  "INC",
  "DEC",
  "SWAP",
  "PRINT",
  "QUESTION",
  "INPUT",
  "LINPUT",
  "TRUE",
  "FALSE",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "SEMICOLON",
  "EQ",
  "EQEQ",
  "NOTEQ",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "NOT",
  "ANDAND",
  "OROR",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "INTEGER_DIV",
  "BIT_AND",
  "BIT_OR",
  "BIT_XOR",
  "BIT_NOT",
  "LSHIFT",
  "RSHIFT",
  "NUMBER",
  "DECIMAL",
  "STRING",
  "IDENTIFIER_STRING",
  "IDENTIFIER_DECIMAL",
  "IDENTIFIER_INTEGER",
  "LABEL",
  "LINEEND",
  "COLON",
  "UMINUS"
  };
}

