
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 21 01:03:52 CST 2018
//----------------------------------------------------

package jsmilebasic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 42;
  public static final int LTEQ = 40;
  public static final int LPAREN = 30;
  public static final int CONTINUE = 15;
  public static final int REPEAT = 13;
  public static final int OUT = 20;
  public static final int FOR = 9;
  public static final int RPAREN = 31;
  public static final int OROR = 45;
  public static final int NOT = 43;
  public static final int LT = 39;
  public static final int ELSEIF = 5;
  public static final int COMMA = 34;
  public static final int INC = 24;
  public static final int ANDAND = 44;
  public static final int UNTIL = 14;
  public static final int NEXT = 10;
  public static final int IF = 2;
  public static final int IDENTIFIER_INTEGER = 49;
  public static final int DIM = 23;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int WEND = 12;
  public static final int EQEQ = 37;
  public static final int NUMBER = 46;
  public static final int BREAK = 16;
  public static final int EQ = 36;
  public static final int LBRACK = 32;
  public static final int LINEEND = 50;
  public static final int COLON = 35;
  public static final int ENDIF = 6;
  public static final int ELSE = 4;
  public static final int STOP = 17;
  public static final int RBRACK = 33;
  public static final int TO = 7;
  public static final int WHILE = 11;
  public static final int IDENTIFIER_DECIMAL = 48;
  public static final int THEN = 3;
  public static final int IDENTIFIER_STRING = 47;
  public static final int END = 21;
  public static final int DEF = 18;
  public static final int DEC = 25;
  public static final int FALSE = 29;
  public static final int GT = 41;
  public static final int SWAP = 26;
  public static final int VAR = 22;
  public static final int PRINT = 27;
  public static final int NOTEQ = 38;
  public static final int STEP = 8;
}

